### ISSUE TITLE
Question: How can I check the mount point for dvdcli in mountinfo

### ISSUE THREAD

**Issue by gyliu513** [emccode/dvdcli#17]
When I run the command "dvdcli mount", I can see that I can mount successfully, but the problem is how can I check the mount point via namespace?

I was using `convoy` as backend.

```
root@mesos002:~# convoy list
{}
root@mesos002:~# dvdcli mount --volumedriver=convoy --volumename=dvd-mesos
INFO[0000] /root/nfs-vol1/dvd-mesos
/root/nfs-vol1/dvd-mesos
root@mesos002:~# cat /proc/self/mountinfo  | grep dvd-mesos
root@mesos002:~#
```

Why did there is no mount point in my host `mountinfo`? How can I check this mount point in mount namespace? Thanks!

**Comment by clintkitson** [comment]
@jay-lau Have you tried the `dvdcli path --volumedriver=convoy --volumename=dvd-mesos` command?

I typically look to `cat /proc/mounts` to view the mounts which should include the one listed as long as you have access to the PID1 mount namespace.

**Comment by gyliu513** [comment]
@clintonskitson Yes, I know that I can use `dvdcli path --volumedriver=convoy --volumename=dvd-mesos`, but what I want to do is I want to see how can I check this via mount info, such as mounts, mountinfo etc, but neither of them can show me the info, do you know why?

Since the mount point is `/root/nfs-vol1/dvd-mesos`, why I cannot see it in system mount table?

```
root@mesos002:~# dvdcli path --volumedriver=convoy --volumename=dvd-mesos
INFO[0000] /root/nfs-vol1/dvd-mesos
/root/nfs-vol1/dvd-mesos
root@mesos002:~# cat /proc/mounts | grep dvd-mesos
root@mesos002:~# cat /proc/self/mountinfo | grep dvd-mesos
root@mesos002:~#
```

**Comment by clintkitson** [comment]
It is possible that the mount namespace that convoy is using isn't the same as what you are trying to reference here. Can you try doing a `docker exec containerpid cat /proc/mounts` from the convoy container?

**Comment by gyliu513** [comment]
Thanks @clintonskitson , now two questions want to get your help:

1) 

```
root@mesos002:/tmp# docker exec  ebadbe5114c9 cat /proc/mounts |grep dvd-mesos
root@mesos002:/tmp# docker exec  ebadbe5114c9 cat /proc/self/mountinfo |grep dvd-mesos
107 89 8:1 /var/lib/docker/volumes/dvd-mesos/_data /tmp rw,relatime - ext4 /dev/disk/by-uuid/017a354d-62b9-4ca2-aca2-12df8da6c82e rw,errors=remount-ro,data=ordered
```

From above, you can see that I can see the mount point from `/proc/self/mountinfo` but not `/proc/mounts`, do you know why?

2) But how can I check the mountpoint if I did not create a container? If I do not create a container using this volume, but run `convoy delete dvd-mesos`, it will be failed with following errors. I know that the mountpoint was in use, but I do not know in which namespace can I find the mountinfo for the volume of dvd-mesos, any comments on this? Thanks!

```
root@mesos002:/proc/3069# convoy delete dvd-mesos
ERRO[0000] Error response from server, Cannot delete volume 8b416bd0-4df8-444f-a56b-73b089bd6081. It is still mounted

{
    "Error": "Error response from server, Cannot delete volume 8b416bd0-4df8-444f-a56b-73b089bd6081. It is still mounted\n"
}
```

**Comment by clintkitson** [comment]
1) If you look at the mapped volumes, I am assuming the listing you are getting is from the PID1 mount space.

2) You could traverse the namespace's mountinfo files and find which owned the volume?

`awk '$9 == "proc" {print FILENAME,$0}' /proc/*/task/*/mountinfo | sort -k2 -u`

**Comment by gyliu513** [comment]
Thanks @clintonskitson , for 1), can you please show me some command to clarify?

For 2), not quite catch your  point, in which namespace shall I find? Because there is no container now.

**Comment by clintkitson** [comment]
`docker inspect containerid` and find the bind/volumes to see if the /proc folder is coming in.

**Comment by clintkitson** [comment]
On the second, the command that I sent will list the `mountinfo` files for each container. If a container has a volume, you could review it there.

**Comment by clintkitson** [comment]
@jay-lau Can you close this if satisfied?

**Comment by gyliu513** [comment]
Thanks @clintonskitson!
