### ISSUE TITLE
Enable simple one line install for CoreOS and Mesosphere

### ISSUE THREAD

**Issue by clintkitson** [emccode/dvdcli#6]

**Comment by clintkitson** [comment]
The placement of the bin within the `/opt/dvdcli/bin/` dir and the setting of the path should satisfy the requirements here.

**Comment by akutz** [comment]
Hi @clintonskitson,

Why is this assigned to me? I'm not working on this project and don't know anything about it or how to test it.

**Comment by akutz** [comment]
Hi @clintonskitson,

I think this should be satisfied with RR's issue https://github.com/emccode/rexray/issues/108
